server:
  port: 8080
spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:devicedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
